spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: sw5
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
